services:
  postgres:
    container_name: postgres_debug
    image: postgres:13.3
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data:cached
    networks:
      - backend_debug

  redis:
    image: redis
    container_name: redis_debug
    restart: unless-stopped
    ports:
        - '6379:6379'
    networks:
      - backend_debug



networks:
  backend_debug:


volumes:
  db_data:
